/**
 * generate-sitemap.mjs — build-time generator for sitemap.xml and robots.txt.
 *
 * Runs before `vite build` (see package.json) so the emitted files land in
 * public/ and are copied verbatim into dist/. The route list and per-route
 * priority/changefreq live in src/seo/siteMeta.js — the single source of truth
 * shared with the runtime <Seo> component, so the sitemap can never drift from
 * what the app actually renders.
 *
 * Override the production origin without code changes:
 *   VITE_SITE_URL=https://www.amcar.ge node scripts/generate-sitemap.mjs
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { ROUTES, SITE_URL as CONFIG_SITE_URL } from "../src/seo/siteMeta.js";

const SITE_URL = (process.env.VITE_SITE_URL || CONFIG_SITE_URL).replace(/\/+$/, "");
const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = resolve(__dirname, "..", "public");

const lastmod = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

const indexable = ROUTES.filter((r) => r.indexable !== false);

const urlEntries = indexable
  .map((r) => {
    const loc = `${SITE_URL}${r.path === "/" ? "/" : r.path}`;
    return [
      "  <url>",
      `    <loc>${loc}</loc>`,
      `    <lastmod>${lastmod}</lastmod>`,
      `    <changefreq>${r.changefreq || "monthly"}</changefreq>`,
      `    <priority>${(r.priority ?? 0.5).toFixed(1)}</priority>`,
      "  </url>",
    ].join("\n");
  })
  .join("\n");

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>
`;

const robots = `# robots.txt — generated by scripts/generate-sitemap.mjs
# Allow full crawl of all public pages; expose the sitemap for discovery.

User-agent: *
Allow: /

# Keep crawlers out of build/asset internals that carry no standalone SEO value.
Disallow: /assets/

Sitemap: ${SITE_URL}/sitemap.xml
`;

writeFileSync(resolve(publicDir, "sitemap.xml"), sitemap, "utf8");
writeFileSync(resolve(publicDir, "robots.txt"), robots, "utf8");

console.log(
  `[seo] wrote sitemap.xml (${indexable.length} urls) and robots.txt for ${SITE_URL}`
);
